name: GitHub Classroom Workflow

on: [push, pull_request]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1

  version:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(github.event.head_commit.author.name, 'GitHub Action') }}
    needs: [ build ]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      executed: ${{ steps.step1.outputs.executed }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - id: step1
        run: echo '::set-output name=executed::true'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Bumps version, updates changelog and creates tag. Adds [skip ci] to commit message to prevent infinite workflow loop
      - name: Tag release
        run: |
          git fetch --unshallow --tags
          git config --global user.email "${{github.event.pusher.email}}"
          git config --global user.name "${{github.event.pusher.name}}"
          npx --yes commit-and-tag-version
          message=`git log -1 --pretty=format:%B | cat`
          git commit --amend -m "$message
          [skip ci]"
          tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          git tag -f $tag
          git push --atomic --no-verify origin main $tag
